apiVersion: apps/v1
kind: Deployment
metadata:
  name: regtech-app-stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: regtech-app-stage
  template:
    metadata:
      labels:
        app: regtech-app-stage
    spec:
      containers:
      - name: regtech-app
        image: <dockerhub-username>/regtech-app:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: regtech-app-service
spec:
  selector:
    app: regtech-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
