apiVersion: apps/v1
kind: Deployment
metadata:
  name: regtech-app-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: regtech-app-dev
  template:
    metadata:
      labels:
        app: regtech-app-dev
    spec:
      containers:
      - name: regtech-app
        image: <dockerhub-username>/regtech-app:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: regtech-app-service-stage
  namespace: dev
  labels:
    app: regtech-app
spec:
  selector:
    app: regtech-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

