apiVersion: v1
kind: Secret
metadata:
  name: regtech-app-secrets
  namespace: prod
data:
  db-password: <base64_encoded_password>
type: Opaque
apiVersion: apps/v1
kind: Deployment
metadata:
  name: regtech-app-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: regtech-app-prod
  template:
    metadata:
      labels:
        app: regtech-app-prod
    spec:
      containers:
      - name: regtech-app
        image: <dockerhub-username>/regtech-app:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: regtech-app-service-prod
  namespace: prod
  labels:
    app: regtech-app
spec:
  selector:
    app: regtech-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

